/* date = January 8th 2021 9:01 pm */

#ifndef FLIGHTCONTROL_PROGRAM_OPTIONS_H
#define FLIGHTCONTROL_PROGRAM_OPTIONS_H

#define PERMANENT_STORAGE_SIZE (MEGABYTES(64))
#define TRANSIENT_STORAGE_SIZE (GIGABYTES( 1))
#define DEBUG_CONSOLE_BUFFER_SIZE       (4096)

#define INITIAL_WINDOW_HEIGHT (720)
#define INITIAL_WINDOW_WIDTH  (1280)


#endif //FLIGHTCONTROL_PROGRAM_OPTIONS_H
